[package]
name = "local-ip-resolver"
version = "0.1.0"
authors = ["rustysec <russ@infocyte.com>"]
edition = "2018"
build = "build.rs"

[target.'cfg(windows)'.dependencies.winapi]
version = "0.3"
features = [
    "inaddr"
]

[profile.release]
lto = true
